version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: mariadb123
      MARIADB_USER: leasing
      MARIADB_PASSWORD: leasing
      MARIADB_DATABASE: leasingcontracts
