spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/leasingcontracts
    username: leasing
    password: leasing
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
    open-in-view: false

server:
  error:
    include-message: always

flyway:
  url: jdbc:mariadb://localhost:3306/leasingcontracts